version: 2
jobs:
  build:
    working_directory: ~/health-check-library
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install && yarn add mocha
      - run:
          name: Run tests
          command: $(yarn bin)/mocha -C -t 10000 **/*.test.js~node_modules/*
