version: 2
jobs:
  build:
    working_directory: ~/health-check-library
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: $(npm bin)/mocha -C -t 10000 javascript/**/*.test.js
