version: 2
jobs:
  build:
    working_directory: ~/health-check-library
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: mocha -C -t 10000 -R xunit-file **/*.test.js~node_modules/*
