#!/usr/bin/env zsh

export NODE_ENV=preprod

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.21.0/install.sh | bash
source ~/.nvm/nvm.sh

cd $WORKSPACE

# install/use the right nodejs version
nvm install
nvm use

# install dependencies
npm install

# Any subsequent commands which fail will cause the shell script to exit immediately
set -e

# Allow extended globbing (see fellow)
setopt extended_glob;

# run tests
XUNIT_FILE=junit.xml `npm bin`/mocha -C -t 10000 -R xunit-file **/*.test.js~node_modules/*

# run check-build
`npm bin`/check-build
